#include <cstddef>
#include <cstdint>
#include <cstring>
#include <vector>

#include "core/batch.h"
#include "simd/kernels.h"

// Drives both the AVX2 (when available) and scalar filter kernels on
// fuzzer-generated bytes. The first 4 bytes are the threshold, the rest is
// the int32 data buffer. Both kernels must produce identical bitmaps for
// any input.
extern "C" int LLVMFuzzerTestOneInput(const uint8_t* data, size_t size) {
    using namespace columnstore;

    if (size < 8) {
        return 0;
    }
    int32_t threshold = 0;
    std::memcpy(&threshold, data, sizeof(int32_t));
    const uint8_t* tail = data + 4;
    size_t tail_size = size - 4;
    const size_t n = tail_size / sizeof(int32_t);
    if (n == 0) {
        return 0;
    }

    std::vector<int32_t> col(n);
    std::memcpy(col.data(), tail, n * sizeof(int32_t));

    std::vector<uint8_t> bm_scalar(Batch<int32_t>::bitmap_bytes(n), 0);
    const std::size_t passed = filter_int32_lt_scalar(col.data(), n, threshold, bm_scalar.data());
    (void)passed;

#if defined(COLUMNSTORE_COMPILED_WITH_AVX2)
    std::vector<uint8_t> bm_avx2(Batch<int32_t>::bitmap_bytes(n), 0);
    filter_int32_lt_avx2(col.data(), n, threshold, bm_avx2.data());
    // Bit-exact comparison over the meaningful bits.
    for (std::size_t i = 0; i < n; ++i) {
        const bool a = (bm_avx2[i / 8] >> (i % 8)) & 1u;
        const bool b = (bm_scalar[i / 8] >> (i % 8)) & 1u;
        if (a != b) {
            __builtin_trap();
        }
    }
#endif
    return 0;
}
